### ISSUE TITLE
Argon2id.ComputeHash requires the hash be exactly 128 bytes long

### ISSUE THREAD

**Issue by Joy-less** [samuel-lucas6/Geralt#14]
First of all, I'm not sure why `MinHashSize` is 93, or why there's a `MaxHashSize` of 128, seems a bit random to me.
But anyway, `ComputeHash` only allows a hash of size 128.

Here's the source code:
```cs
public static void ComputeHash(Span<byte> hash, ReadOnlySpan<byte> password, int iterations, int memorySize)
{
    Validation.EqualToSize(nameof(hash), hash.Length, MaxHashSize); // Issue?
    Validation.NotLessThanMin(nameof(iterations), iterations, MinIterations);
    Validation.NotLessThanMin(nameof(memorySize), memorySize, MinMemorySize);
    Sodium.Initialize();
    int ret = crypto_pwhash_str_alg(hash, password, (ulong)password.Length, (ulong)iterations, (nuint)memorySize, crypto_pwhash_argon2id_ALG_ARGON2ID13);
    if (ret != 0) { throw new InsufficientMemoryException("Insufficient memory to perform password hashing."); }
}
```

I think it should instead be:
```cs
Validation.SizeBetween(nameof(hash), hash.Length, MinHashSize, MaxHashSize);
```
Just like in `VerifyHash`.

**Comment by samuel-lucas6** [comment]
Hi, thanks for using Geralt.

This is because of `crypto_pwhash_STRBYTES` in [libsodium](https://github.com/jedisct1/libsodium/blob/1.0.20-RELEASE/src/libsodium/include/sodium/crypto_pwhash.h#L49), which is [128 bytes](https://github.com/jedisct1/libsodium/blob/1.0.20-RELEASE/src/libsodium/include/sodium/crypto_pwhash_argon2id.h#L41). From the libsodium [documentation](https://doc.libsodium.org/password_hashing/default_phf#password-storage):

> out must be a dedicated storage area that’s large enough to hold crypto_pwhash_STRBYTES bytes, but the actual output string may be shorter.

So this is correct. I agree it seems weird, but this is what has to be done when using a span buffer rather than return. The output is padded and can be truncated to remove the padding.

`VerifyHash()` is a bit different because the output from `ComputeHash()` isn't a fixed length (if you ignore the padding) and the libsodium function accepts a shorter string. `MinHashSize` was calculated based on things like the string prefix and encoded parameters for Argon2id but could be smaller to allow Argon2i and non-libsodium strings to be verified if I'm remembering correctly.

**Comment by Joy-less** [comment]
@samuel-lucas6 Thanks for responding and creating this repository.
I've set the hash length to 128 and it seems to work correctly. Please can you tell me if I'm using this in the intended way?
Thank you.

```cs
public const int HashLength = 128;
public const int SaltLength = 32;
public const int Iterations = 3;
public const int MemorySize = 32_000;
public static readonly Encoding Encoding = Encoding.UTF8;

public static async Task<string> HashAsync(string Input, string? Salt = null) {
    return await Task.Run(() => {
        Span<byte> Output = stackalloc byte[HashLength];
        Argon2id.ComputeHash(Output, Encoding.GetBytes(Input + Salt), iterations: Iterations, memorySize: MemorySize);
        return Encoding.GetString(Output);
    });
}
public static async Task<bool> VerifyAsync(string Input, string Hash, string? Salt = null) {
    return await Task.Run(() => {
        return Argon2id.VerifyHash(Encoding.GetBytes(Hash), Encoding.GetBytes(Input + Salt));
    });
}
```

**Comment by samuel-lucas6** [comment]
> Please can you tell me if I'm using this in the intended way?

You don't need to provide a salt to these functions. `ComputeHash()` randomly generates a salt and `VerifyHash()` automatically retrieves the salt encoded in the string output. That's why there's no `salt` parameter, but I'll update the docs to make this clear.

In terms of other comments, you should never have an optional salt when password hashing, there's no need to define your own `HashLength` and `SaltLength` constants (in fact, libsodium only supports 16 byte salts unfortunately), and I'd recommend against using a string for storing the password if possible (see if you can use a char array instead so it can be wiped). I'm adding some functions that will assist with secure memory.

**Comment by Joy-less** [comment]
> > Please can you tell me if I'm using this in the intended way?
> 
> You don't need to provide a salt to these functions. `ComputeHash()` randomly generates a salt and `VerifyHash()` automatically retrieves the salt encoded in the string output. That's why there's no `salt` parameter, but I'll update the docs to make this clear.
> 
> In terms of other comments, you should never have an optional salt when password hashing, there's no need to define your own `HashLength` and `SaltLength` constants (in fact, libsodium only supports 16 byte salts unfortunately), and I'd recommend against using a string for storing the password if possible (see if you can use a char array instead so it can be wiped). I'm adding some functions that will assist with secure memory.

Thanks for your response.

If Geralt or libsodium is automatically generating and extracting a salt, how can I make sure a salt is being used? I hashed the UTF8 bytes of the string "abcdef" twice and got:
```
$argon2id$v=19$m=31,t=3,p=1$zpZmd/2ovOevxTkzNYG85A$EKjR6NL4T63VuV7vhoSinDbGh96scyUVmN1sMn6tWu8
$argon2id$v=19$m=31,t=3,p=1$/E27Byacr5pm/hBYJ2uxAg$+ka+awDRp6Hkyb9VXbESZDKiymRCtMptFnkgZcvH290
```
Which part of these strings is the salt?

As for the `HashLength` and `SaltLength` constants, which constant should I use for the hash size?
```
MinHashSize = 93 // Why 93?
MaxHashSize = 128 // Will this stay the same?
```

**Comment by samuel-lucas6** [comment]
> how can I make sure a salt is being used?

Notice how `$argon2id$v=19$m=31,t=3,p=1$` remains the same, whereas the second half changes. That's because of the salt. The salt is the first part of the second half between the two `$` symbols, and the actual hash is the last part of the string after the final `$`. The salt is 16 bytes, and the hash output is 32 bytes.

So the salts are:

```
zpZmd/2ovOevxTkzNYG85A
/E27Byacr5pm/hBYJ2uxAg
```

> As for the HashLength and SaltLength constants, which constant should I use for the hash size?

You should use `MaxHashSize` for the reasons I've already explained. As mentioned in the [docs](https://www.geralt.xyz/password-hashing#computehash), you can either keep the null padding characters or truncate the null characters after converting the bytes to a string.

`MinHashSize` is purely for validation when verifying a hash; you can ignore it completely if you're only verifying strings produced by `ComputeHash()`. It's 93 because that's what I calculated the minimum hash size to be for Argon2id hash strings produced by this library. If you're using another library, you could produce shorter strings (e.g., by using a smaller salt).

In this case, you don't need a salt length constant at all. For `DeriveKey()`, you can use `SaltSize`.

**Comment by Joy-less** [comment]
> The salt is 16 bytes, and the hash output is 32 bytes.
> 
> So the salts are:
> ```
> zpZmd/2ovOevxTkzNYG85A
> /E27Byacr5pm/hBYJ2uxAg
> ```

Thanks for your response again. I'm just a bit confused about this. I thought that was the case, but those are not 16 characters. They are 22 characters.
Since they're UTF8 ASCII characters, one character should equal one byte. So what are the extra 6 characters?

**Comment by samuel-lucas6** [comment]
> Since they're UTF8 ASCII characters, one character should equal one byte. So what are the extra 6 characters?

These are [Base64 characters](https://blog.aaronlenoir.com/2017/11/10/get-original-length-from-base-64-string/). Everything is done with bytes and then converted to a string.

**Comment by Joy-less** [comment]
> public const int HashLength = 128;
> public const int SaltLength = 32;
> public const int Iterations = 3;
> public const int MemorySize = 32_000;
> public static readonly Encoding Encoding = Encoding.UTF8;

If someone is reading this, the example I gave has an unresolved issue. `MemorySize` should not be as low as `32_000` (32kB); it should be at least `32_000_000` (32MB). That's why it was always extremely fast to hash even at high iterations.
