### ISSUE TITLE
Different shared secrets

### ISSUE THREAD

**Issue by shipitfaster** [samuel-lucas6/Geralt#8]
I have two public/private key pairs that do not generate the same shared secret when calling into X25519.ComputeSharedKey(). I may not have a firm understanding of limitations with the type of keys I can use, but these keys are both used in blockchain signing and verification. They are both 32 bytes.

**Comment by samuel-lucas6** [comment]
There are a few things that could be going wrong here. For example, are you passing in the private and public key of the same key pair or the private key of one key pair and the public key of the other key pair?

Also, there's no method called `X25519.ComputeSharedKey()`, so which method are you referring to? The public and private keys should be generated using `X25519.GenerateKeyPair()`.

**Comment by shipitfaster** [comment]
Sorry, I meant ComputeSharedSecret().

I've confirmed the keys are being passed in correctly ala the test cases.  AlicePrivate, BobPublic and then BobPrivate,AlicePublic. 

The only thing I can think of is that I did not generate these keys myself via GenerateKeyPair() but rather they are the private/public keys assigned via the HashPack crypto wallet (which I would not expect broad knowledge of here). 

What might be helpful is understanding if there is a way to verify that a private and public key match. Would signing and verifying accomplish this?

**Comment by samuel-lucas6** [comment]
No worries. I must apologise as well because I managed to overlook the blockchain signing/verifying part, which suggests the keys are probably for Ed25519. However, Ed25519 private keys are 64 bytes in libsodium instead of 32 to prevent an [API issue](https://github.com/MystenLabs/ed25519-unsafe-libs) that can cause private key exposure.

To use those keys (if they're Ed25519 keys), you would have to concatenate `privateKey || publicKey` and use that as the private key. You then need to use `Ed25519.GetX25519PublicKey()` and `Ed25519.GetX25519PrivateKey()` to convert the Ed25519 keys to X25519 keys for key exchange. Note that it's not recommended to use a key pair for more than one purpose (e.g. signing and key exchange); separate key pairs should be used when possible.

Finally, I wouldn't recommend using `X25519.ComputeSharedSecret()`. `X25519.DeriveSenderSharedKey()` and `X25519.DeriveRecipientSharedKey()` prevent vulnerabilities in some scenarios.

**Comment by shipitfaster** [comment]
Wow lots of hoops here. :) I was able to get this working with your help, so thank you. 

>  Note that it's not recommended to use a key pair for more than one purpose (e.g. signing and key exchange); separate key pairs should be used when possible.

Given a crypto wallet is limited to a single public key, it seems to make sense to reserve this key for signing only and generate a new pair each time you wish to engage with a new recipient. Here's the [public docs on ED25519 Keys on Hedera](https://docs.hedera.com/hedera/sdks-and-apis/sdks/keys/generate-a-new-key-pair) if you're inclined. Thanks again for the help!

**Comment by samuel-lucas6** [comment]
Glad you got it working!
